version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run:
          name: Install JUnit coverage reporter
          command: npm install --save-dev jest-junit

      # run tests!
      - run:
          name: "Run tests with JUnit as reporter"
          command: npm run testci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"

      - store_test_results:
          path: "./reports/junit/js-test-results.xml"

      - store_artifacts:
          path: "./reports/junit/js-test-results.xml"
